blog/urls.py
from django.urls import path, include
from blog import urls
from . import views

urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('aboutus', views.AboutUs.as_view(), name="aboutus"),
    path('post/<int:pk>', views.PostDetail, name='postdetail'),
    path('newpost', views.newpost, name='newpost'),
    path('usrinfo', views.user_image_func, name='usrinfo'),
    path('postedit/<int:pk>', views.PostEdit.as_view(), name='postedit'),
    path('postdelete/<int:pk>', views.BlogDelete.as_view(), name='postdelete'),
    path('mypost/<author>', views.MyPost.as_view(), name='myposts'),
    path('commentreplydelete/<int:pk>', views.CommentReplyDelete.as_view(), name='commentreplydelete'),
    path('commentdelete/<int:pk>', views.CommentDelete.as_view(), name='commentdelete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('post/postnew', views.BlogPostNew.as_view(), name='postnew'),
    path('profile/<str:nam>', views.profile, name='profile'),
    path('editprofileinfo/<int:pk>', views.userInfoFormView, name='editprofileinfo'),
    path('search', views.search, name='search'),
    path('category/<str:hashtags>', views.categoryview, name='category'),

]

trynewblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
import os
from PIL import Image

# Create your models here.

class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


def get_topbanner_filename(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "documents/banner/{}/{}".format(slug, filename)

class Blog(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=200, null=True, blank=True)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    star = models.PositiveIntegerField(default=0)
    topbanner =  models.ImageField(upload_to=get_topbanner_filename, null=True, blank=True)
    category  = models.ForeignKey(Hashtag,  on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('postdetail', args=[str(self.id)])

#, default='documents/03.jpg'


def get_image_filename(instance, filename):
    title = instance.blog.id
    slug = slugify(title)
    return "post_images/post_images_{}/{}".format(slug, filename)


class Document(models.Model):
    blog = models.ForeignKey(Blog, default=None, on_delete=models.CASCADE)
    image = models.FileField(upload_to=get_image_filename, verbose_name = 'Image')

    def filename(self):
        return os.path.basename(self.image.name)

#-----------------------------------------------------------

def get_user_image_filename(instance, filename):
    title = instance.author
    slug = slugify(title)
    return "user_image_{}/{}".format(slug, filename)

class UserImage(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, default=True)
    myimage = models.ImageField(upload_to=get_user_image_filename, default='user_image_noimg/jobs.jpg', null=True, blank=True)


#------------------------------------------------------

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.message


class CommentReply(models.Model):
    whichcomment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    message = models.CharField(max_length = 250)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)

    

    def __str__(self):
        return self.message





#------------------------------------------------------

class UserInfo(models.Model):
    author = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    displayname = models.CharField(max_length=50, null=True, blank=True)
    designation = models.CharField(max_length=50, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    views = models.PositiveIntegerField(default = 0)

    def get_absolute_url(self):
        return reverse('homepage')

#-------------------------------------------------------

templates/base.html
<!DOCTYPE html>
<html >
<head>
  <!-- Site made with Mobirise Website Builder v4.7.0, https://mobirise.com -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise v4.7.0, mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  {% load static %}
  <link rel="shortcut icon" href="{% static 'assets/images/logo2.png' %}" type="image/x-icon">
  <meta name="description" content="Web Site Maker Description">
  <title>homepage</title>
  <link rel="stylesheet" href="{% static 'assets/web/assets/mobirise-icons/mobirise-icons.css' %}">
  <link rel="stylesheet" href="{% static 'assets/tether/tether.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/dropdown/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/mobirise/css/mbr-additional.css' %}" type="text/css">
  
<style>
.hashtagsinp:hover{
    text-decoration: underline;
}
</style>
  
</head>  


<body>

{% load static %}
<script src="{% static 'assets/web/assets/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/popper/popper.min.js' %}"></script>
<script src="{% static 'assets/tether/tether.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/smoothscroll/smooth-scroll.js' %}"></script>
<script src="{% static 'assets/dropdown/js/script.min.js' %}"></script>
<script src="{% static 'assets/touchswipe/jquery.touch-swipe.min.js' %}"></script>
<script src="{% static 'assets/theme/js/script.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/shortcuts/infinite.js"></script>


  <section class="menu cid-qOrcLPjtgR" once="menu" id="menu1-h">
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="{% url 'homepage' %}">
                        {% load static %}
                         <img src="{% static 'assets/images/TIGER-res.png' %}" alt="" title="" style="height: 3.8rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="{% url 'homepage' %}">BlogVlog</a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">

                <li class="nav-item">
                    <form class="form-inline" method="GET" action="{% url 'search' %}">

                        <input class="form-control mr-sm-2" id="id_q" name="q" type="search" placeholder="Search Blog" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </li>

                <li class="nav-item dropdown open">
                        <a class="nav-link link text-white display-4" data-toggle="modal" data-target="#categoryModal" href="#">
                            <span class="mbri-setting2 mbr-iconfont mbr-iconfont-btn"></span>
                                Category
                        </a>
        
                </li>
                <li class="nav-item">
                    <a class="nav-link link text-white display-4" href="{% url 'aboutus' %}">
                        <span class="mbri-search mbr-iconfont mbr-iconfont-btn"></span>
                        About Us
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown open">
                        <a class="nav-link link text-white dropdown-toggle display-4" href="https://mobirise.com" data-toggle="dropdown-submenu" aria-expanded="true">
                            <span class="mbri-smile-face mbr-iconfont mbr-iconfont-btn"></span>
                            {{ request.user.first_name|truncatechars:22 }}
                        </a>
                        <div class="dropdown-menu">
                            <a class="text-white dropdown-item display-4" href="{% url 'profile' request.user %}">Profile</a>
                            
                            <a class="text-white dropdown-item display-4" href="{% url 'newpost' %}">New Post</a>
                           <hr>
                            <a class="btn btn-sm btn-warning display-4" href="{% url 'logout' %}">
                                <span class="mbri-play mbr-iconfont mbr-iconfont-btn"></span>
                                    Logout
                            </a>
                        </div>
                    </li>
                
                {% else %}
                <li>
                <a class="btn btn-sm btn-primary display-4" href="{% url 'login' %}">
                    <span class="mbri-play mbr-iconfont mbr-iconfont-btn"></span>
                    Login
                </a>
            </li>
                {% endif %}
        </ul>
        </div>
    </nav>
</section>


{% block body %}

{% endblock %}

<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Category</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            {% for hashtags in hashtag %}
                <a href="{% url 'category' hashtags%}" class="hashtagsinp">&nbsp;#{{hashtags}}&nbsp;&nbsp;</a>
            {% endfor %}
                    </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal" style="padding:4%;">Close</button>
        </div>
        </div>
    </div>
</div>

templates/basecrop.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.css" rel="stylesheet">
    
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.0.0/cropper.js"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

templates/blogedit.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<button type="submit">submit</button>
</form>

templates/details mockup.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block body %}



<section class="mbr-section content5 cid-qOrpftxYjK mbr-parallax-background" id="content5-z">

    <div class="mbr-overlay" style="opacity: 0.7; background-color: rgb(0, 0, 0);">
    </div>

    <div class="container">
        <div class="media-container-row">
            <div class="title col-12 col-md-8">
                <h2 class="align-center mbr-bold mbr-white pb-3 mbr-fonts-style display-1">
                    {{ data1.title }}<br></h2>
                <h3 class="mbr-section-subtitle align-center mbr-light mbr-white pb-3 mbr-fonts-style display-5">
                    {{ data1.subtitle }}
                </h3>
                
            </div>
        </div>
    </div>
</section>

<style>
    
    .cid-qOrpftxYjK{
        background-image: url("{{ data1.topbanner.url }}");
    }
</style>
<section class="mbr-section article content1 cid-qOrqewdLpP" id="content1-14" >


    <div class="container">
        <div class="media-container-row">
            <div class="mbr-text col-12 col-md-8 mbr-fonts-style display-5">
                
                <h6><i>Total words - {{ data1.text|wordcount }}</i></h6>

                {% autoescape off %}
                {{ data1.text }}
                {% endautoescape %}

                <img src="" class="img-fluid img-thumbnail" alt="">
                {% load static%}

                <p>{{ data1.document.url}}</p>
                <p>{{ data1.document.name }}</p>

            </div>
        </div>
    </div>
</section>









<section class="testimonials3 cid-qOrqR1IiVK" id="testimonials3-17">

        <div class="container">
            <div class="media-container-row">
                <div class="media-content px-3 align-self-center mbr-white py-2">
                    <p class="mbr-text testimonial-text mbr-fonts-style display-7">
                       About the author
                    </p>
                    <p class="mbr-author-name pt-4 mbr-fonts-style display-3">
                       <a href="{% url 'profile' authorinfo.author %}" class="mbr-fonts-style text-black">{{userinfo_object.displayname }} </a>
                    </p>
                    <p class="mbr-author-desc mbr-fonts-style display-7">
                       {{userinfo_object.designation}}
                    </p>
                </div>
                <div class="mbr-figure pl-lg-5">
                  <img src="/media/{{authorinfo.myimage}}" height="100%" width="100%">
                </div>
            </div>
        </div>
    </section>
    




<!-- comments section code -->
{% if user.is_authenticated %}

<div class="row">
<div class="col-sm-12 col-md-8 offset-md-2" >
<br>
<h4>Post Comments:</h4><hr>
<form method="POST">
{% csrf_token %}
{% for field in form1.visible_fields %}

    <div class="form-group">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
    </div>
{% endfor %}

<button type="submit" class="btn btn-warning">Add Comment</button>

</form>
<br>
<hr>
<br>
</div>
</div>

<div class="container">
{% for comments in com %}

<div class="comment mb-1 row">
    <div class="comment-avatar col-md-2 col-sm-2 col-xs-2 text-center  d-none d-sm-block">
        <a href=""><img class="mx-auto rounded-circle img-fluid" src="/media/{{ comments.usrimg.myimage }}" alt="avatar"></a>
    </div>
    <div class="comment-content col-md-10 col-sm-9 col-xs-9">
        <h6 class="small comment-meta"><a href="#">{{comments.user}}</a> Today, 2:38</h6>       
        <div class="comment-body">
            <h5>
                {{ comments.message }}</h5>{% if comments.user == request.user %}<a href="{% url 'commentdelete' comments.pk %}" class="small"><span class="badge badge-primary">delete</span></a>{% endif %}
            
        </div>
        <div class="replybutton" style="">
            <span class="text-right small"> Reply</span>
        </div>

    <div class="row replybox" style="display: none">
        <div class="col-sm-12 ml-5 pl-5">
            <form method='POST'>
                {% csrf_token %}
                <input type="hidden" name='whichcomment' id='id_whichcomment' value="{{comments.id}}">
                <input class="" type="text" name='message' maxlength="250" id="id_message" placeholder="Reply. . . ">
                <button style="padding:1%;" class="btn" type="submit">submit</button>
            </form>
        </div>
    </div>
</div>
</div>
<br>



{% for r in replycom %}
{% if r.whichcomment.message == comments.message %}



<div class="comment-reply col-md-11 offset-md-1 col-sm-10 offset-sm-2">
        <div class="row">

            <div class="comment-avatar col-md-1 col-sm-2 text-center pr-1  d-none d-sm-block">
                <a href=""><img class="mx-auto rounded-circle img-fluid" src="/media/{{ r.usrimg.myimage }}" alt="avatar"></a>
            </div>
            <div class="comment-content col-md-11 col-sm-10 col-12">
                <h6 class="small comment-meta"><a href="#">{{r.user}}</a> Today, 12:31</h6>
                <div class="comment-body">
                    <h5>{{ r.message }}</h5>{% if r.user == request.user %}<a href="{% url 'commentreplydelete' r.pk %}" class="small"><span class="badge badge-primary">delete</span></a>{% endif %}
            </div>
        </div>
    </div>
</div>



{% endif %}
{% endfor %}
<br><hr>
{% endfor %}
</div>
{% else %}


<section class="mbr-section info2 cid-qOrr15WCRi" id="info2-19">
        <div class="container">
           <div class="row main justify-content-center">
               <div class="media-container-column col-12 col-lg-3 col-md-4">
                   <div class="mbr-section-btn align-left py-4">
                       <a class="btn btn-primary display-4" href="{% url 'login' %}" target="_blank">
                       <span class="mbri-cursor-click mbr-iconfont"></span>
                       &nbsp;OKAY!
                       </a>
                   </div>
               </div>
               <div class="media-container-column title col-12 col-lg-7 col-md-6">
                   <h2 class="align-right mbr-bold mbr-white pb-3 mbr-fonts-style display-2">LOGIN TO SEE COMMENTS</h2>
                   <h3 class="mbr-section-subtitle align-right mbr-light mbr-white mbr-fonts-style display-5">and enjoy various other features like reading, liking, commenting, connecting, posting etc.</h3>
               </div>
           </div>
       </div>
   </section>
   


{% endif %}




<br><hr>




<section once="" class="cid-qOrru7r8z5" id="footer7-1a">
    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="row row-links">
                <ul class="foot-menu">
                <li class="foot-menu-item mbr-fonts-style display-7">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li><li class="foot-menu-item mbr-fonts-style display-7">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</li><li class="foot-menu-item mbr-fonts-style display-7">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</li><li class="foot-menu-item mbr-fonts-style display-7"></li><li class="foot-menu-item mbr-fonts-style display-7">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</li></ul>
            </div>
            <div class="row social-row">
                <div class="social-list align-right pb-2">

                <div class="soc-item">
                        <a href="https://twitter.com/mohitjain2302" target="_blank">
                            <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="https://www.facebook.com/mohitjain2302" target="_blank">
                            <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="https://www.youtube.com/technomonk" target="_blank">
                            <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="https://instagram.com/frasm__" target="_blank">
                            <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="socicon-googleplus socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div><div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="socicon-behance socicon mbr-iconfont mbr-iconfont-social"></span>
                        </a>
                    </div></div>
            </div>
            <div class="row row-copirayt">
                <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                    © Copyright 2017 Mobirise - All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</section>








<script>


        $(document).ready(function(){
            $('img').each(function(){
              var src = $(this).attr('src');;
              $(this).attr('src', src.replace('post_images_i','post_images_{{data1.id}}'));
            });
          });


        $('.replybutton').click( function(){
            $(this).next('.replybox').toggle();
            console.log('triggered');

        });
      

</script>
</body>
</html>

{% endblock %}

templates/editinfo.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block body %}

<br>
<br><br>
<hr>
<div class="container">
<div class="row">
  <div class="col-sm-12 col-md-8 offset-md-2">
<h3>Lets Edit Profile  -</h3><hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
    {% endfor %}

{% for field in form.visible_fields %}

    <div class="form-group">
      {{ field.label_tag }}

        {% render_field field class="form-control" %}
        <span class="text-danger">{{ field.errors }}</span>
        
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
<br>
  <hr><br>

    <button type="submit" class="btn btn-success">Post Blog</button>
    <a href="{% url 'homepage' %}" class="btn btn-danger">Cancel</a>
  </form>
</div></div>
</div>
{% endblock %}

templates/editingpost.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block body %}

<br>
<br><br>
<hr>
{% for d in documentdata %}

{{d}}<br>
{{d.image}}<br>
{{d.image.url}}<br>


{% endfor %}
<br><br><hr>

<h3>Lets Edit Post  -</h3><hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
    {% endfor %}

{% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

        {% render_field field class="form-control" %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}
<br>
  <hr><br>
    {{ formset.management_form }}
    {% for form in formset %}
    {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
     {% endfor %}
    {% endfor %}


    <button type="submit" class="btn btn-success">Post Blog</button>
    <a href="{% url 'homepage' %}" class="btn btn-danger">Cancel</a>
  </form>


{% endblock %}

templates/login.html
<h2>Login</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Login</button>
</form>

templates/poatnew.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_p}}
<button type="submit">submit</button>
</form>

templates/postdetail.html
<a href="{% url 'homepage' %}">Homepage</a>
<br><hr>
<h2>{{ data1.title }}</h2>
<h4>{{ data1.author }}</h4>
<h5>{{ data1.text }}</h5>

<br>
<a href="{% url 'postdelete' data1.pk %}"><u>delete</u></a>
<br>
<h3>comments</h3>
<form method="POST">
{% csrf_token %}

{{ form1 }}

<button type="submit">submit</button>

</form>
<br>
<hr>
<br>


{% for comments in com %}
<p>{{ comments.user }} ---
{{ comments.message }}&nbsp;&nbsp;{% if comments.user == request.user %}<a href="{% url 'commentdelete' comments.pk %}">delete</a>{% endif %}
<br>
<form method='POST'>
    {% csrf_token %}

    <label for="id_whichcomment">whichcomment</label>
    <input type="hidden" name='whichcomment' id='id_whichcomment' value="{{comments.id}}">
    &nbsp;
    <label for="id_message">Message:</label>
    <input type="text" name='message' maxlength="250" id="id_message">

    <button type="button" id="ajaxbutton">ajax submit</button>
    
    <button type="submit">submit</button>
</form>
<ul>
{% for r in replycom %}


{% if r.whichcomment.message == comments.message %}

<li><blockquote>{{r.user }} -- {{ r.message }}&nbsp;&nbsp;{% if r.user == request.user %}<a href="{% url 'commentreplydelete' r.pk %}">delete</a>{% endif %}</blockquote></li>

{% endif %}

{% endfor %}
</ul></p>

<br>
{% endfor %}





















<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

<script>
    $("#ajaxbutton").click(function (){
        $ajax({
            type: "POST",
            url: "{% url 'postdetaill' data1.id %}",
            data: {"message":$("#id_message").val(), "whichcomment": $("#id_whichcomment").val()},
            beforeSend:function(xhr){
                xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));  
            },
            success:function(data,textStatus){
                $("#id_message").val("update");
            },
            error:function(XMLHttpRequest, textStatus, errorThrown){
                alert(XMLHttpRequest.responseText);
            }
        });
        return false;
    });
</script>

templates/signup.html
<h2>Sign up</h2>
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Sign up</button>
</form>